### ISSUE TITLE
error in installing the package 

### ISSUE THREAD

**Issue by salimoha** [Sandia-Labs/PVLIB_Python#45]
I get the following error during my installation on a linux machine? How can I install this package?

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/pandas/tests/test_index.py'

Storing debug log for failure in /home/alimo/.pip/pip.log

**Comment by wholmgren** [comment]
This ``Sandia-Labs/PVLIB_Python`` repository is not maintained. All pvlib-python development now takes place at 

https://github.com/pvlib/pvlib-python

Please use the new package and report issues at that repository. 

That being said, it looks like maybe you're trying to install pvlib in your system's python directory, in which case you'd need to use sudo. I recommend using a virtual environment instead. The anaconda distribution makes this easy.

**Comment by salimoha** [comment]
I don't have problem in Mac OS. However, I have problem installing it in Linux machines and windows

I do the following in terminal:
git clone https://github.com/pvlib/pvlib-python.git
cd pvlib-python/
pip install .

Then I get the above-mentioned errors.

**Comment by wholmgren** [comment]
Looking at the error message again, it appears that your problem may be specific to your pandas installation. Perhaps you have an older version of pandas already installed on your Linux/windows machines and the setup script is trying to upgrade it. Two questions:

* What version of pandas do you have installed?
* Can you ``pip install pandas --upgrade --no-deps``?

Also, the pvlib-python pandas requirement was very recently changed from ``0.15`` to ``0.13.1``, so you might try pulling the latest pvlib-python master.

**Comment by salimoha** [comment]
pip install pandas --upgrade --no-deps

I get the following error after that:
I've tried to fix it but I couldn't do that. I was wondering if you could help me to fix this error.

 
Downloading/unpacking pandas from https://pypi.python.org/packages/source/p/pandas/pandas-0.16.0.tar.gz#md5=bfe311f05dc0c351f8955fbd1e296e73
  Downloading pandas-0.16.0.tar.gz (4.8MB): 4.8MB downloaded
  Running setup.py (path:/tmp/pip_build_salimoha/pandas/setup.py) egg_info for package pandas
    
    warning: no files found matching 'README.rst'
    no previously-included directories found matching 'doc/build'
    warning: no directories found matching 'examples'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '#*' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '*.png' found anywhere in distribution
Installing collected packages: pandas
  Found existing installation: pandas 0.13.1
    Uninstalling pandas:
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/pandas/version.py'

Storing debug log for failure in /home/salimoha/.pip/pip.log

**Comment by bmu** [comment]
You don't have permissions for the folder, were pandas should be installed.
Either you have to use `sudo`, ask your admins or create a virtual environment in a folder were you have write permissions. You can find some informations on how to do this in the [pvlib wiki](https://github.com/pvlib/pvlib-python/wiki/Development-information).

**Comment by wholmgren** [comment]
I think you'll find that this is a lot easier if you use the anaconda distribution

http://docs.continuum.io/anaconda/install.html

**Comment by salimoha** [comment]
I did:

$conda install pandas

and then went to the pvlib directory did:

$pip install .


Thank you it worked!

On Tue, Apr 7, 2015 at 8:34 AM, Will Holmgren <notifications@github.com>
wrote:

> I think you'll find that this is a lot easier if you use the anaconda
> distribution
>
> http://docs.continuum.io/anaconda/install.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sandia-Labs/PVLIB_Python/issues/45#issuecomment-90611832>
> .
>



-- 
Shahrouz Alimohammadi, M.Sc.
Graduate Researcher, Ph.D. student.
Mechanical and Aerospace Engineering
University of California San Diego
http://solar.ucsd.edu/
salimoha@ucsd.edu
